using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Terraria.ModLoader;

namespace CalamityMod.Systems.Collections;

public sealed class DonatorsNameList : ModSystem
{
	public static IList<string> List { get; private set; }

	internal static IList<string> NewPatreonList { get; private set; }

	internal static IList<string> OriginalPatreonList { get; private set; }

	public override void OnModLoad()
	{
		int num = 138;
		List<string> list = new List<string>(num);
		CollectionsMarshal.SetCount(list, num);
		Span<string> span = CollectionsMarshal.AsSpan(list);
		int num2 = 0;
		span[num2] = "Aerosyn";
		num2++;
		span[num2] = "Aidan Spears";
		num2++;
		span[num2] = "Amandalias";
		num2++;
		span[num2] = "Arcadia";
		num2++;
		span[num2] = "Arcxus";
		num2++;
		span[num2] = "Ariallis";
		num2++;
		span[num2] = "asokasi";
		num2++;
		span[num2] = "Audrey Lynn Beemus";
		num2++;
		span[num2] = "awesomechapro";
		num2++;
		span[num2] = "Azariah";
		num2++;
		span[num2] = "azazel";
		num2++;
		span[num2] = "Ballin";
		num2++;
		span[num2] = "Barrett Turner";
		num2++;
		span[num2] = "BlueRay_256";
		num2++;
		span[num2] = "Boomdiada";
		num2++;
		span[num2] = "Borb9834";
		num2++;
		span[num2] = "botbot94";
		num2++;
		span[num2] = "Bwlstorm";
		num2++;
		span[num2] = "c0d3_404";
		num2++;
		span[num2] = "Carduelis";
		num2++;
		span[num2] = "Careless_imp";
		num2++;
		span[num2] = "Chin";
		num2++;
		span[num2] = "ChristmadLaner";
		num2++;
		span[num2] = "Chuck";
		num2++;
		span[num2] = "Cinder";
		num2++;
		span[num2] = "Cosmoec Ark";
		num2++;
		span[num2] = "Cosmore";
		num2++;
		span[num2] = "Cracking cheese gromit";
		num2++;
		span[num2] = "CrazyGamer69";
		num2++;
		span[num2] = "Darthlego";
		num2++;
		span[num2] = "DefinitlyResponsible";
		num2++;
		span[num2] = "Diamond Nife";
		num2++;
		span[num2] = "Dizzetriya";
		num2++;
		span[num2] = "djsnj20";
		num2++;
		span[num2] = "DOGMA";
		num2++;
		span[num2] = "DogVTF";
		num2++;
		span[num2] = "Dokuro vibes";
		num2++;
		span[num2] = "Dos Champion";
		num2++;
		span[num2] = "drake093104";
		num2++;
		span[num2] = "Entrian";
		num2++;
		span[num2] = "Equinoxux";
		num2++;
		span[num2] = "FishBread";
		num2++;
		span[num2] = "goo";
		num2++;
		span[num2] = "Grant Curtiss";
		num2++;
		span[num2] = "GrayAeternum";
		num2++;
		span[num2] = "haefer.goat.oats";
		num2++;
		span[num2] = "Halleyvetica";
		num2++;
		span[num2] = "Hamsting";
		num2++;
		span[num2] = "help";
		num2++;
		span[num2] = "HeWhoShallNotBeBaned";
		num2++;
		span[num2] = "Hunyre";
		num2++;
		span[num2] = "Hyperthermia";
		num2++;
		span[num2] = "Idan";
		num2++;
		span[num2] = "Iptktp9";
		num2++;
		span[num2] = "J.U.N.E.S";
		num2++;
		span[num2] = "Jace Ufret";
		num2++;
		span[num2] = "Jalapeno9";
		num2++;
		span[num2] = "Jankle";
		num2++;
		span[num2] = "JFL";
		num2++;
		span[num2] = "JmWarrior";
		num2++;
		span[num2] = "JMww2";
		num2++;
		span[num2] = "JOSEPH BRACKEN";
		num2++;
		span[num2] = "JustinTheLocalToaster";
		num2++;
		span[num2] = "Kelta7";
		num2++;
		span[num2] = "Kiddorox";
		num2++;
		span[num2] = "Lazy2ns";
		num2++;
		span[num2] = "LecTrouble";
		num2++;
		span[num2] = "Liam Healy";
		num2++;
		span[num2] = "Liam Rafle";
		num2++;
		span[num2] = "Magicoal";
		num2++;
		span[num2] = "Mateo Sauvege";
		num2++;
		span[num2] = "Mediocre King";
		num2++;
		span[num2] = "Melongun";
		num2++;
		span[num2] = "Mint_loll";
		num2++;
		span[num2] = "Misako Drevis";
		num2++;
		span[num2] = "MizzUltraViolet DamienTK";
		num2++;
		span[num2] = "Moe";
		num2++;
		span[num2] = "MrDizzyG";
		num2++;
		span[num2] = "Natalie Webb";
		num2++;
		span[num2] = "Nature";
		num2++;
		span[num2] = "niceguysrage";
		num2++;
		span[num2] = "Nick H";
		num2++;
		span[num2] = "Nightinglade";
		num2++;
		span[num2] = "Nothin Purrsonal";
		num2++;
		span[num2] = "Nova Solarius";
		num2++;
		span[num2] = "Nyavalcade";
		num2++;
		span[num2] = "NyxxyNightstar";
		num2++;
		span[num2] = "OakhamSam";
		num2++;
		span[num2] = "OriasTheFloof";
		num2++;
		span[num2] = "Oxytoxy365";
		num2++;
		span[num2] = "Ozone-278";
		num2++;
		span[num2] = "PantySlack";
		num2++;
		span[num2] = "Patch357";
		num2++;
		span[num2] = "Patrick Nevermore";
		num2++;
		span[num2] = "Phil Broome";
		num2++;
		span[num2] = "PumpkinKing";
		num2++;
		span[num2] = "Qwertz";
		num2++;
		span[num2] = "Reece";
		num2++;
		span[num2] = "RK";
		num2++;
		span[num2] = "roryoftheabyss";
		num2++;
		span[num2] = "RuskieThe3rd";
		num2++;
		span[num2] = "Ryo Tadashi";
		num2++;
		span[num2] = "Sable";
		num2++;
		span[num2] = "SakuraWinterz";
		num2++;
		span[num2] = "Salted Warlock";
		num2++;
		span[num2] = "schmoovi";
		num2++;
		span[num2] = "Sharktank6";
		num2++;
		span[num2] = "SirChaos189";
		num2++;
		span[num2] = "SkeletonHunter96";
		num2++;
		span[num2] = "SRMG267";
		num2++;
		span[num2] = "tadict";
		num2++;
		span[num2] = "Taelishe";
		num2++;
		span[num2] = "Taylor Olligoci";
		num2++;
		span[num2] = "Tethox";
		num2++;
		span[num2] = "That Katsafaros";
		num2++;
		span[num2] = "The Deer Who Sold The World";
		num2++;
		span[num2] = "The Roborex";
		num2++;
		span[num2] = "The Wither";
		num2++;
		span[num2] = "Trinity Series";
		num2++;
		span[num2] = "Tsukara";
		num2++;
		span[num2] = "Umbara";
		num2++;
		span[num2] = "Vanillin";
		num2++;
		span[num2] = "VentCrab";
		num2++;
		span[num2] = "Vergil Cyrus";
		num2++;
		span[num2] = "Vertigo";
		num2++;
		span[num2] = "Vixcalibur";
		num2++;
		span[num2] = "Vortex";
		num2++;
		span[num2] = "weisslerren";
		num2++;
		span[num2] = "Willye";
		num2++;
		span[num2] = "wt55030";
		num2++;
		span[num2] = "xAqult";
		num2++;
		span[num2] = "Xtra Trinity 3678";
		num2++;
		span[num2] = "Xtra";
		num2++;
		span[num2] = "Xzier_Tengal";
		num2++;
		span[num2] = "YashimaYamanata";
		num2++;
		span[num2] = "Zachtoplasm";
		num2++;
		span[num2] = "Zecro";
		num2++;
		span[num2] = "ZoeyPlague";
		NewPatreonList = list;
		num2 = 618;
		List<string> list2 = new List<string>(num2);
		CollectionsMarshal.SetCount(list2, num2);
		Span<string> span2 = CollectionsMarshal.AsSpan(list2);
		num = 0;
		span2[num] = "_Skeggy_";
		num++;
		span2[num] = "116taj";
		num++;
		span2[num] = "26-4-1";
		num++;
		span2[num] = "2Larry2";
		num++;
		span2[num] = "3en";
		num++;
		span2[num] = "3x1t_5tyl3";
		num++;
		span2[num] = "A_Normal_Person";
		num++;
		span2[num] = "adain";
		num++;
		span2[num] = "Adamko";
		num++;
		span2[num] = "Aden C.N.";
		num++;
		span2[num] = "Aero";
		num++;
		span2[num] = "Aero (Aero#4599)";
		num++;
		span2[num] = "Aeroni";
		num++;
		span2[num] = "Æthereal";
		num++;
		span2[num] = "Afzofa";
		num++;
		span2[num] = "Aidan";
		num++;
		span2[num] = "Akkolite";
		num++;
		span2[num] = "Albino gonkvader";
		num++;
		span2[num] = "Alec";
		num++;
		span2[num] = "Aleksanders";
		num++;
		span2[num] = "Aleksh";
		num++;
		span2[num] = "Alex";
		num++;
		span2[num] = "Alex N";
		num++;
		span2[num] = "Alexander";
		num++;
		span2[num] = "Alexis";
		num++;
		span2[num] = "Alfragiste";
		num++;
		span2[num] = "Allegro";
		num++;
		span2[num] = "allosar";
		num++;
		span2[num] = "Ally2Cute";
		num++;
		span2[num] = "Altzeus";
		num++;
		span2[num] = "anglerraptor";
		num++;
		span2[num] = "Anish";
		num++;
		span2[num] = "Anton";
		num++;
		span2[num] = "Antonie";
		num++;
		span2[num] = "anything5000";
		num++;
		span2[num] = "Apotheosis";
		num++;
		span2[num] = "apotofkoolaid";
		num++;
		span2[num] = "Arche";
		num++;
		span2[num] = "Archie";
		num++;
		span2[num] = "Ari";
		num++;
		span2[num] = "Ariscottle";
		num++;
		span2[num] = "Arkhine";
		num++;
		span2[num] = "Arthur";
		num++;
		span2[num] = "Arti";
		num++;
		span2[num] = "asdf935";
		num++;
		span2[num] = "Ash";
		num++;
		span2[num] = "Ashamper";
		num++;
		span2[num] = "Asheel";
		num++;
		span2[num] = "Ashton";
		num++;
		span2[num] = "Ashton";
		num++;
		span2[num] = "Avery";
		num++;
		span2[num] = "Azura";
		num++;
		span2[num] = "Azure";
		num++;
		span2[num] = "Azzilan";
		num++;
		span2[num] = "BakaQing";
		num++;
		span2[num] = "Barbara";
		num++;
		span2[num] = "Ben";
		num++;
		span2[num] = "Bendy";
		num++;
		span2[num] = "Beta165";
		num++;
		span2[num] = "bikmin";
		num++;
		span2[num] = "Bill";
		num++;
		span2[num] = "Billy";
		num++;
		span2[num] = "Blackbluue";
		num++;
		span2[num] = "Bladesaber";
		num++;
		span2[num] = "Blobby6799";
		num++;
		span2[num] = "BobIsNotMyRealName";
		num++;
		span2[num] = "Boomdiada";
		num++;
		span2[num] = "Borb9834";
		num++;
		span2[num] = "Bossy Punch";
		num++;
		span2[num] = "Braden";
		num++;
		span2[num] = "BreachNClear747";
		num++;
		span2[num] = "Bread";
		num++;
		span2[num] = "Brendan";
		num++;
		span2[num] = "Brian";
		num++;
		span2[num] = "Brian";
		num++;
		span2[num] = "Briny_Coffee";
		num++;
		span2[num] = "Broken Faucet";
		num++;
		span2[num] = "Bruggs";
		num++;
		span2[num] = "Bruh.PNG";
		num++;
		span2[num] = "Brutus";
		num++;
		span2[num] = "Brutzli";
		num++;
		span2[num] = "BumbleDoge";
		num++;
		span2[num] = "Buppercups - Roblox";
		num++;
		span2[num] = "CaineSenpai";
		num++;
		span2[num] = "Calcium Comrade";
		num++;
		span2[num] = "callisto";
		num++;
		span2[num] = "Cameron";
		num++;
		span2[num] = "Cameron";
		num++;
		span2[num] = "Carboniferous";
		num++;
		span2[num] = "CasualNoLifer";
		num++;
		span2[num] = "Cerberus";
		num++;
		span2[num] = "Chaos";
		num++;
		span2[num] = "ChAoS DiScOrD";
		num++;
		span2[num] = "ChaosChaos";
		num++;
		span2[num] = "Chaotic Reks";
		num++;
		span2[num] = "Chaozhi";
		num++;
		span2[num] = "Charles";
		num++;
		span2[num] = "Check pins";
		num++;
		span2[num] = "Cheddar";
		num++;
		span2[num] = "Chigbungus";
		num++;
		span2[num] = "Chip";
		num++;
		span2[num] = "Chow Chow";
		num++;
		span2[num] = "ChrigTopher";
		num++;
		span2[num] = "Christopher";
		num++;
		span2[num] = "Circuit-Jay";
		num++;
		span2[num] = "cocodezi_";
		num++;
		span2[num] = "Cody";
		num++;
		span2[num] = "Cole";
		num++;
		span2[num] = "Colin";
		num++;
		span2[num] = "Colin V";
		num++;
		span2[num] = "Commander Frostbite";
		num++;
		span2[num] = "Conner";
		num++;
		span2[num] = "Coolguystorm YT";
		num++;
		span2[num] = "Corn M. Cobb";
		num++;
		span2[num] = "cosmickalamity";
		num++;
		span2[num] = "CosmicStarIight";
		num++;
		span2[num] = "CrabBar";
		num++;
		span2[num] = "Creamy";
		num++;
		span2[num] = "CrimsonCrips";
		num++;
		span2[num] = "Crippling-Ambition";
		num++;
		span2[num] = "Cristian(Mihaii)";
		num++;
		span2[num] = "Crysthamyr";
		num++;
		span2[num] = "Culex";
		num++;
		span2[num] = "Curtis";
		num++;
		span2[num] = "cytokat";
		num++;
		span2[num] = "Daawnz";
		num++;
		span2[num] = "Dakota";
		num++;
		span2[num] = "Dakota C";
		num++;
		span2[num] = "DanYami";
		num++;
		span2[num] = "DaPyRo";
		num++;
		span2[num] = "darkhawke";
		num++;
		span2[num] = "Darkus";
		num++;
		span2[num] = "Darkweb";
		num++;
		span2[num] = "Darren";
		num++;
		span2[num] = "Darthlego";
		num++;
		span2[num] = "Dasdruid";
		num++;
		span2[num] = "dawn thunder";
		num++;
		span2[num] = "dawnboi";
		num++;
		span2[num] = "Dayne";
		num++;
		span2[num] = "ddoogg88 tdog";
		num++;
		span2[num] = "Deallly";
		num++;
		span2[num] = "Dee";
		num++;
		span2[num] = "DeLordeyeee";
		num++;
		span2[num] = "DemoN K!ng";
		num++;
		span2[num] = "dennis";
		num++;
		span2[num] = "Depressed Dad Gaming";
		num++;
		span2[num] = "Derdjin";
		num++;
		span2[num] = "DESPACITO";
		num++;
		span2[num] = "Destiny Stallcup";
		num++;
		span2[num] = "Destructoid";
		num++;
		span2[num] = "DevAesthetic";
		num++;
		span2[num] = "DevilSunrise";
		num++;
		span2[num] = "Devin";
		num++;
		span2[num] = "Devon";
		num++;
		span2[num] = "Devonte";
		num++;
		span2[num] = "dexxer65";
		num++;
		span2[num] = "Dionysos";
		num++;
		span2[num] = "discokittie";
		num++;
		span2[num] = "DjackV";
		num++;
		span2[num] = "djsnj20";
		num++;
		span2[num] = "Domrinth";
		num++;
		span2[num] = "Done";
		num++;
		span2[num] = "Doodled_lynx";
		num++;
		span2[num] = "Doug";
		num++;
		span2[num] = "Doveda";
		num++;
		span2[num] = "Dr. Pawsworth";
		num++;
		span2[num] = "Drakkece";
		num++;
		span2[num] = "drenmus!";
		num++;
		span2[num] = "Drip Veezy";
		num++;
		span2[num] = "Driser";
		num++;
		span2[num] = "Duck Satan";
		num++;
		span2[num] = "Dull";
		num++;
		span2[num] = "dummyAzure";
		num++;
		span2[num] = "Dylan";
		num++;
		span2[num] = "Eddie Spaghetti";
		num++;
		span2[num] = "EdelVollMilch";
		num++;
		span2[num] = "edm vibes";
		num++;
		span2[num] = "Ein";
		num++;
		span2[num] = "Eisaya";
		num++;
		span2[num] = "Ekun";
		num++;
		span2[num] = "Elementari";
		num++;
		span2[num] = "Elfinlocks";
		num++;
		span2[num] = "Elijah";
		num++;
		span2[num] = "Empress Vega";
		num++;
		span2[num] = "Eragon3942";
		num++;
		span2[num] = "Eric";
		num++;
		span2[num] = "Eternal Silence";
		num++;
		span2[num] = "ethan";
		num++;
		span2[num] = "Ethan";
		num++;
		span2[num] = "everquartz";
		num++;
		span2[num] = "F00d Demon";
		num++;
		span2[num] = "Face";
		num++;
		span2[num] = "FaeLoPondering";
		num++;
		span2[num] = "False";
		num++;
		span2[num] = "Fartein";
		num++;
		span2[num] = "Faye";
		num++;
		span2[num] = "Feels Fishy";
		num++;
		span2[num] = "Ferret4T";
		num++;
		span2[num] = "Finnrua";
		num++;
		span2[num] = "fire";
		num++;
		span2[num] = "Fish Repairs";
		num++;
		span2[num] = "FishBread";
		num++;
		span2[num] = "Fizzlpoprock";
		num++;
		span2[num] = "Florian";
		num++;
		span2[num] = "Forge";
		num++;
		span2[num] = "Freakish";
		num++;
		span2[num] = "Frederik";
		num++;
		span2[num] = "Fweepachino";
		num++;
		span2[num] = "Gameology";
		num++;
		span2[num] = "GameRDheAsianSandwich";
		num++;
		span2[num] = "Gamma Freya";
		num++;
		span2[num] = "garfu";
		num++;
		span2[num] = "GentSkeleton";
		num++;
		span2[num] = "Georgios";
		num++;
		span2[num] = "Gibb50";
		num++;
		span2[num] = "GIGA MAN";
		num++;
		span2[num] = "Gilded Gryphon";
		num++;
		span2[num] = "Glaid";
		num++;
		span2[num] = "gluten tag";
		num++;
		span2[num] = "Goblin";
		num++;
		span2[num] = "Goober";
		num++;
		span2[num] = "Goomfrontlut";
		num++;
		span2[num] = "GP";
		num++;
		span2[num] = "GreenBerry";
		num++;
		span2[num] = "GreenTea";
		num++;
		span2[num] = "GregTheSpinarak";
		num++;
		span2[num] = "Gretchen";
		num++;
		span2[num] = "Griffin";
		num++;
		span2[num] = "Grylken";
		num++;
		span2[num] = "GTW High Cube";
		num++;
		span2[num] = "Guwahavel";
		num++;
		span2[num] = "Habb";
		num++;
		span2[num] = "Hana";
		num++;
		span2[num] = "Handburger";
		num++;
		span2[num] = "Hannes";
		num++;
		span2[num] = "Hans Volter";
		num++;
		span2[num] = "happy thoughts";
		num++;
		span2[num] = "Hargestar";
		num++;
		span2[num] = "Hayden";
		num++;
		span2[num] = "Hayden";
		num++;
		span2[num] = "Helixas";
		num++;
		span2[num] = "HellGoat2";
		num++;
		span2[num] = "High Charity";
		num++;
		span2[num] = "Him";
		num++;
		span2[num] = "Himakaze";
		num++;
		span2[num] = "Hokojin";
		num++;
		span2[num] = "Homunculus Derelictus";
		num++;
		span2[num] = "hoosfire";
		num++;
		span2[num] = "hubert thieblot";
		num++;
		span2[num] = "Hunter";
		num++;
		span2[num] = "Iconic Parker Gaming";
		num++;
		span2[num] = "Iguy";
		num++;
		span2[num] = "Indeciiissive";
		num++;
		span2[num] = "IsaacInsomnia";
		num++;
		span2[num] = "Izuna";
		num++;
		span2[num] = "J.U.N.E.S";
		num++;
		span2[num] = "Jack";
		num++;
		span2[num] = "JackShizz";
		num++;
		span2[num] = "Jackson";
		num++;
		span2[num] = "Jakob";
		num++;
		span2[num] = "Jalapeno9";
		num++;
		span2[num] = "James";
		num++;
		span2[num] = "James";
		num++;
		span2[num] = "Jankle";
		num++;
		span2[num] = "Jarod";
		num++;
		span2[num] = "Javyz";
		num++;
		span2[num] = "Jaydon";
		num++;
		span2[num] = "Jaykob";
		num++;
		span2[num] = "jc.";
		num++;
		span2[num] = "Jeff";
		num++;
		span2[num] = "Jeff";
		num++;
		span2[num] = "Jenonen";
		num++;
		span2[num] = "JensB__";
		num++;
		span2[num] = "Jersey";
		num++;
		span2[num] = "jes";
		num++;
		span2[num] = "Jessire";
		num++;
		span2[num] = "Jetpat3";
		num++;
		span2[num] = "Jheybyrd";
		num++;
		span2[num] = "jjth0m3";
		num++;
		span2[num] = "Joe";
		num++;
		span2[num] = "Joep";
		num++;
		span2[num] = "Jordan";
		num++;
		span2[num] = "Jose";
		num++;
		span2[num] = "Joshua";
		num++;
		span2[num] = "julius";
		num++;
		span2[num] = "Just a random guy";
		num++;
		span2[num] = "just akkolite";
		num++;
		span2[num] = "JustLonelyPi";
		num++;
		span2[num] = "Kaden";
		num++;
		span2[num] = "Kaimonick";
		num++;
		span2[num] = "Kaledoulas";
		num++;
		span2[num] = "KAT-G307";
		num++;
		span2[num] = "Katherine";
		num++;
		span2[num] = "Kazurgundu";
		num++;
		span2[num] = "KeL";
		num++;
		span2[num] = "Kevin";
		num++;
		span2[num] = "Kevin";
		num++;
		span2[num] = "kgh8090";
		num++;
		span2[num] = "Kinzoku";
		num++;
		span2[num] = "Kipluck";
		num++;
		span2[num] = "Kiyotu";
		num++;
		span2[num] = "KJ";
		num++;
		span2[num] = "Konorango";
		num++;
		span2[num] = "Korb Orb";
		num++;
		span2[num] = "Krankwagon";
		num++;
		span2[num] = "KugelBlitz";
		num++;
		span2[num] = "KurlozClown";
		num++;
		span2[num] = "Lacuna";
		num++;
		span2[num] = "Lady Shira";
		num++;
		span2[num] = "Lagohz";
		num++;
		span2[num] = "Lance";
		num++;
		span2[num] = "Landon";
		num++;
		span2[num] = "Larry That Barry";
		num++;
		span2[num] = "Lauren";
		num++;
		span2[num] = "Leonidas";
		num++;
		span2[num] = "Levi";
		num++;
		span2[num] = "Levi";
		num++;
		span2[num] = "Lightedflare";
		num++;
		span2[num] = "Lilith";
		num++;
		span2[num] = "Lime-Wars l 1";
		num++;
		span2[num] = "Littlepiggy";
		num++;
		span2[num] = "Lodude";
		num++;
		span2[num] = "LompL";
		num++;
		span2[num] = "Lord_Lucerne";
		num++;
		span2[num] = "Loser";
		num++;
		span2[num] = "Lucas";
		num++;
		span2[num] = "Lucas";
		num++;
		span2[num] = "LucasHM";
		num++;
		span2[num] = "LucasTwocas";
		num++;
		span2[num] = "Lucazii";
		num++;
		span2[num] = "Luis";
		num++;
		span2[num] = "Luke";
		num++;
		span2[num] = "LumiEvi";
		num++;
		span2[num] = "LvL-94";
		num++;
		span2[num] = "M001NG";
		num++;
		span2[num] = "Madd Cat";
		num++;
		span2[num] = "Magic Love";
		num++;
		span2[num] = "Magicoal";
		num++;
		span2[num] = "MajinBagel";
		num++;
		span2[num] = "Malik";
		num++;
		span2[num] = "Marco";
		num++;
		span2[num] = "Marissa443";
		num++;
		span2[num] = "Mark";
		num++;
		span2[num] = "Markie";
		num++;
		span2[num] = "Marko";
		num++;
		span2[num] = "Mars";
		num++;
		span2[num] = "martyrdomination";
		num++;
		span2[num] = "Maskedmilo";
		num++;
		span2[num] = "Mathuantie";
		num++;
		span2[num] = "Matias";
		num++;
		span2[num] = "Matthew";
		num++;
		span2[num] = "Max Kim";
		num++;
		span2[num] = "MaxingOut";
		num++;
		span2[num] = "Mayhem";
		num++;
		span2[num] = "MeanieG";
		num++;
		span2[num] = "Medi";
		num++;
		span2[num] = "Melvin";
		num++;
		span2[num] = "Mendzey";
		num++;
		span2[num] = "Meow";
		num++;
		span2[num] = "Merubel";
		num++;
		span2[num] = "Met Vox";
		num++;
		span2[num] = "Mikabul";
		num++;
		span2[num] = "Min";
		num++;
		span2[num] = "MingWhy";
		num++;
		span2[num] = "Minty Candy";
		num++;
		span2[num] = "MishiroUsui";
		num++;
		span2[num] = "Misinput";
		num++;
		span2[num] = "MissMudflaps";
		num++;
		span2[num] = "Mister Winchester";
		num++;
		span2[num] = "MittoMan";
		num++;
		span2[num] = "MiyoshiEira";
		num++;
		span2[num] = "Mobian";
		num++;
		span2[num] = "Mohammad";
		num++;
		span2[num] = "Moist Lad";
		num++;
		span2[num] = "Monic";
		num++;
		span2[num] = "Monti";
		num++;
		span2[num] = "Moonicento";
		num++;
		span2[num] = "MovingTarget_086";
		num++;
		span2[num] = "Mr. Bones";
		num++;
		span2[num] = "Mr.Matter";
		num++;
		span2[num] = "MrCreamen";
		num++;
		span2[num] = "MrNobody";
		num++;
		span2[num] = "n0tacat";
		num++;
		span2[num] = "Naglfar";
		num++;
		span2[num] = "Nanaki";
		num++;
		span2[num] = "Natalie";
		num++;
		span2[num] = "Nathan";
		num++;
		span2[num] = "Navigator";
		num++;
		span2[num] = "Ne'er Dowell";
		num++;
		span2[num] = "NEBULA";
		num++;
		span2[num] = "NebulaMagePlays";
		num++;
		span2[num] = "Nemesis 041";
		num++;
		span2[num] = "Neoplasmatic";
		num++;
		span2[num] = "NepNep";
		num++;
		span2[num] = "Nexus";
		num++;
		span2[num] = "Nicholas";
		num++;
		span2[num] = "Nightskyflyer";
		num++;
		span2[num] = "Nitronium Productions";
		num++;
		span2[num] = "Noah";
		num++;
		span2[num] = "NoOneElse";
		num++;
		span2[num] = "Nuclear Chaos";
		num++;
		span2[num] = "Nuclei";
		num++;
		span2[num] = "Number1piratepan";
		num++;
		span2[num] = "NuT NiTe";
		num++;
		span2[num] = "NyanLegacy215";
		num++;
		span2[num] = "Nyapano";
		num++;
		span2[num] = "Nycro";
		num++;
		span2[num] = "Oblivionisbruh";
		num++;
		span2[num] = "Obsoleek";
		num++;
		span2[num] = "Oceanman232";
		num++;
		span2[num] = "OctolingGrimm";
		num++;
		span2[num] = "oli saer";
		num++;
		span2[num] = "Olkothan";
		num++;
		span2[num] = "OnTheAirPogs";
		num++;
		span2[num] = "oracle";
		num++;
		span2[num] = "OriginForme487";
		num++;
		span2[num] = "OrrangProto";
		num++;
		span2[num] = "Orudeon";
		num++;
		span2[num] = "Pacnysam";
		num++;
		span2[num] = "Paltham";
		num++;
		span2[num] = "Patrera";
		num++;
		span2[num] = "Patrick";
		num++;
		span2[num] = "Pedro";
		num++;
		span2[num] = "Perditio Astrum";
		num++;
		span2[num] = "Picasso's Bean";
		num++;
		span2[num] = "Pigeon";
		num++;
		span2[num] = "Plant Waifu";
		num++;
		span2[num] = "Pneuma";
		num++;
		span2[num] = "Pomelo";
		num++;
		span2[num] = "pomp neigh";
		num++;
		span2[num] = "Ponynator";
		num++;
		span2[num] = "Poopifier Poopifly";
		num++;
		span2[num] = "Popsickle Yoshi";
		num++;
		span2[num] = "porglesupreme";
		num++;
		span2[num] = "Potato - Stego";
		num++;
		span2[num] = "Potion Man";
		num++;
		span2[num] = "Preston";
		num++;
		span2[num] = "Primpy";
		num++;
		span2[num] = "Prism";
		num++;
		span2[num] = "Professor Pissington";
		num++;
		span2[num] = "ProfessorWinston";
		num++;
		span2[num] = "Proffesor prostate";
		num++;
		span2[num] = "profoundmango69";
		num++;
		span2[num] = "PsychoGrizzly";
		num++;
		span2[num] = "Pusheen_";
		num++;
		span2[num] = "pyobbo";
		num++;
		span2[num] = "Pyromaniac146";
		num++;
		span2[num] = "Qelrin";
		num++;
		span2[num] = "Rando Calrissian";
		num++;
		span2[num] = "Random Weeb";
		num++;
		span2[num] = "rawpie2";
		num++;
		span2[num] = "Real mystlc";
		num++;
		span2[num] = "Reanamet";
		num++;
		span2[num] = "Reiter splash";
		num++;
		span2[num] = "RetroRed";
		num++;
		span2[num] = "Rinja";
		num++;
		span2[num] = "Rixu";
		num++;
		span2[num] = "RKMoon";
		num++;
		span2[num] = "Robert";
		num++;
		span2[num] = "RockRecker39";
		num++;
		span2[num] = "Rolandark";
		num++;
		span2[num] = "Rooki";
		num++;
		span2[num] = "Rossadon";
		num++;
		span2[num] = "Rottingwood";
		num++;
		span2[num] = "Roxas";
		num++;
		span2[num] = "Ruben";
		num++;
		span2[num] = "RuskieThe3rd";
		num++;
		span2[num] = "Ruthoranium";
		num++;
		span2[num] = "Ryaegos";
		num++;
		span2[num] = "Ryan";
		num++;
		span2[num] = "Ryan";
		num++;
		span2[num] = "Ryan Baker-Ortiz";
		num++;
		span2[num] = "Sabrina";
		num++;
		span2[num] = "Sadouken";
		num++;
		span2[num] = "Sailor Jolt";
		num++;
		span2[num] = "Saladify";
		num++;
		span2[num] = "Samuel";
		num++;
		span2[num] = "Sanctuary";
		num++;
		span2[num] = "Sandblast";
		num++;
		span2[num] = "Sarcosuchus";
		num++;
		span2[num] = "Schlarfblrfsch";
		num++;
		span2[num] = "SCONICBOOM";
		num++;
		span2[num] = "Scribbles";
		num++;
		span2[num] = "Scrumlet";
		num++;
		span2[num] = "Seanツ";
		num++;
		span2[num] = "Sevenfold";
		num++;
		span2[num] = "Shadoku";
		num++;
		span2[num] = "SharZz";
		num++;
		span2[num] = "Shaun";
		num++;
		span2[num] = "sherk";
		num++;
		span2[num] = "Shifter";
		num++;
		span2[num] = "Shiny";
		num++;
		span2[num] = "Shiro";
		num++;
		span2[num] = "Shirosity";
		num++;
		span2[num] = "ShotgunAngel";
		num++;
		span2[num] = "Shpee";
		num++;
		span2[num] = "Sigil";
		num++;
		span2[num] = "sk";
		num++;
		span2[num] = "Skeli_G";
		num++;
		span2[num] = "Slim";
		num++;
		span2[num] = "Smart2004";
		num++;
		span2[num] = "Smug";
		num++;
		span2[num] = "Snowy";
		num++;
		span2[num] = "Soko";
		num++;
		span2[num] = "Solaire";
		num++;
		span2[num] = "SoloMael";
		num++;
		span2[num] = "SolsticeUnlimitd";
		num++;
		span2[num] = "SomeRando";
		num++;
		span2[num] = "SoyScoutSmasher";
		num++;
		span2[num] = "Spider region";
		num++;
		span2[num] = "Spirit Shield";
		num++;
		span2[num] = "Splotchycrib";
		num++;
		span2[num] = "SpookyNinja";
		num++;
		span2[num] = "Squishy";
		num++;
		span2[num] = "srxe";
		num++;
		span2[num] = "Starmitzy";
		num++;
		span2[num] = "StarryFox";
		num++;
		span2[num] = "Steven";
		num++;
		span2[num] = "Stormone";
		num++;
		span2[num] = "Streakist";
		num++;
		span2[num] = "Suicide Dreams";
		num++;
		span2[num] = "Superbeepig";
		num++;
		span2[num] = "sweatingdishes";
		num++;
		span2[num] = "T E R M I N A T O R";
		num++;
		span2[num] = "Tails the Fox 92";
		num++;
		span2[num] = "Taitou1";
		num++;
		span2[num] = "Takeru";
		num++;
		span2[num] = "Talmadge";
		num++;
		span2[num] = "Taylor";
		num++;
		span2[num] = "Team";
		num++;
		span2[num] = "TemperedAether";
		num++;
		span2[num] = "Terrarian Dragon";
		num++;
		span2[num] = "Tervastator";
		num++;
		span2[num] = "Tezguin";
		num++;
		span2[num] = "That Katsafaros";
		num++;
		span2[num] = "The Buildmonger";
		num++;
		span2[num] = "The Davester";
		num++;
		span2[num] = "The Evolution";
		num++;
		span2[num] = "The Goliath";
		num++;
		span2[num] = "The Illustrious Sqouinchuousor";
		num++;
		span2[num] = "The Infinity";
		num++;
		span2[num] = "The Pyro";
		num++;
		span2[num] = "The Roborex";
		num++;
		span2[num] = "The Wolf Commando";
		num++;
		span2[num] = "thebettercat";
		num++;
		span2[num] = "TheBlackHand";
		num++;
		span2[num] = "TheGreatSako";
		num++;
		span2[num] = "theHoopty";
		num++;
		span2[num] = "TheSilverGhost";
		num++;
		span2[num] = "Thomas";
		num++;
		span2[num] = "Thomas";
		num++;
		span2[num] = "ThomasThePencil";
		num++;
		span2[num] = "Thys";
		num++;
		span2[num] = "Timon";
		num++;
		span2[num] = "TitaniumLlama";
		num++;
		span2[num] = "Tomat (Stevie)";
		num++;
		span2[num] = "Tombarry Expresserino";
		num++;
		span2[num] = "topnormal";
		num++;
		span2[num] = "Trinity Series";
		num++;
		span2[num] = "TwanTheGOAT";
		num++;
		span2[num] = "Tweee";
		num++;
		span2[num] = "Tyler";
		num++;
		span2[num] = "Tyler";
		num++;
		span2[num] = "Uberransy";
		num++;
		span2[num] = "Ulmod";
		num++;
		span2[num] = "Ultra Succ";
		num++;
		span2[num] = "Umberto";
		num++;
		span2[num] = "Underlost";
		num++;
		span2[num] = "Valkyrie";
		num++;
		span2[num] = "vcf55";
		num++;
		span2[num] = "Veine";
		num++;
		span2[num] = "velneu";
		num++;
		span2[num] = "VeryMasterNinja";
		num++;
		span2[num] = "Vetus";
		num++;
		span2[num] = "Victor";
		num++;
		span2[num] = "Vimek Xol";
		num++;
		span2[num] = "Vmar98";
		num++;
		span2[num] = "Vorbis";
		num++;
		span2[num] = "Vroomy Has -3,000 IQ";
		num++;
		span2[num] = "Vyster";
		num++;
		span2[num] = "Warlok";
		num++;
		span2[num] = "Whale";
		num++;
		span2[num] = "Whitegiraffe";
		num++;
		span2[num] = "Will";
		num++;
		span2[num] = "william";
		num++;
		span2[num] = "William";
		num++;
		span2[num] = "William";
		num++;
		span2[num] = "WillyDilly";
		num++;
		span2[num] = "WinterTire";
		num++;
		span2[num] = "Wodernet";
		num++;
		span2[num] = "Wolfmaw";
		num++;
		span2[num] = "WrathOfOlympus";
		num++;
		span2[num] = "Xaphlactus";
		num++;
		span2[num] = "xAqult";
		num++;
		span2[num] = "xd Ow0";
		num++;
		span2[num] = "XDkilljoy65XX";
		num++;
		span2[num] = "xElectrix_";
		num++;
		span2[num] = "Xenocrona";
		num++;
		span2[num] = "Xenocrona";
		num++;
		span2[num] = "Xsiana";
		num++;
		span2[num] = "XusTingo9";
		num++;
		span2[num] = "Yatagarasu";
		num++;
		span2[num] = "yayoi";
		num++;
		span2[num] = "Yhashtur";
		num++;
		span2[num] = "yiumik";
		num++;
		span2[num] = "YuH";
		num++;
		span2[num] = "YumeiSenshi";
		num++;
		span2[num] = "Yumi";
		num++;
		span2[num] = "Zacky";
		num++;
		span2[num] = "Zekai";
		num++;
		span2[num] = "Zerafir";
		num++;
		span2[num] = "Zerimore";
		num++;
		span2[num] = "zombie wolf";
		num++;
		span2[num] = "Zombieh";
		num++;
		span2[num] = "zombieseatflesh7";
		num++;
		span2[num] = "Zombified _G";
		num++;
		span2[num] = "ZyferDex_";
		num++;
		span2[num] = "병현 송";
		OriginalPatreonList = list2;
		IList<string> originalPatreonList = OriginalPatreonList;
		IList<string> newPatreonList = NewPatreonList;
		num = originalPatreonList.Count + newPatreonList.Count;
		List<string> list3 = new List<string>(num);
		CollectionsMarshal.SetCount(list3, num);
		Span<string> span3 = CollectionsMarshal.AsSpan(list3);
		num2 = 0;
		foreach (string item in originalPatreonList)
		{
			span3[num2] = item;
			num2++;
		}
		foreach (string item2 in newPatreonList)
		{
			span3[num2] = item2;
			num2++;
		}
		List = list3;
	}

	public override void Unload()
	{
		OriginalPatreonList = null;
		NewPatreonList = null;
		List = null;
	}
}
