<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>CalamityMod</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>14.0</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <CheckForOverflowUnderflow>False</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup />
  <ItemGroup />
  <ItemGroup>
    <Reference Include="MonoMod.Utils" />
    <Reference Include="tModLoader">
      <HintPath>F:\Games\Tmodloader2\tModLoader.dll</HintPath>
    </Reference>
    <Reference Include="FNA" />
    <Reference Include="System.Text.RegularExpressions">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Text.RegularExpressions.dll</HintPath>
    </Reference>
    <Reference Include="log4net" />
    <Reference Include="System.Collections">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Collections.dll</HintPath>
    </Reference>
    <Reference Include="ReLogic" />
    <Reference Include="System.Threading">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Threading.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading.ThreadPool">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Threading.ThreadPool.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.FileSystem.Watcher">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.IO.FileSystem.Watcher.dll</HintPath>
    </Reference>
    <Reference Include="TerrariaHooks" />
    <Reference Include="System.Drawing.Primitives">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Drawing.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="System.Text.Json">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Text.Json.dll</HintPath>
    </Reference>
    <Reference Include="System.IO.Compression">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.IO.Compression.dll</HintPath>
    </Reference>
    <Reference Include="System.Net.Mail">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Net.Mail.dll</HintPath>
    </Reference>
    <Reference Include="Mono.Cecil" />
    <Reference Include="System.Threading.Thread">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Threading.Thread.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Concurrent">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Collections.Concurrent.dll</HintPath>
    </Reference>
    <Reference Include="System.Diagnostics.StackTrace">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Diagnostics.StackTrace.dll</HintPath>
    </Reference>
    <Reference Include="System.Numerics.Vectors">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Numerics.Vectors.dll</HintPath>
    </Reference>
    <Reference Include="MonoMod.RuntimeDetour" />
    <Reference Include="System.Linq">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Linq.dll</HintPath>
    </Reference>
    <Reference Include="System.Runtime.InteropServices">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Runtime.InteropServices.dll</HintPath>
    </Reference>
    <Reference Include="System.Memory">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Memory.dll</HintPath>
    </Reference>
    <Reference Include="System.Threading.Tasks.Parallel">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Threading.Tasks.Parallel.dll</HintPath>
    </Reference>
    <Reference Include="System.ComponentModel.Primitives">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.ComponentModel.Primitives.dll</HintPath>
    </Reference>
    <Reference Include="System.Collections.Immutable">
      <HintPath>..\..\..\..\..\..\..\..\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.14\System.Collections.Immutable.dll</HintPath>
    </Reference>
    <Reference Include="Humanizer" />
  </ItemGroup>
</Project>